[package]
name = "ffi_reflect_test"
version = "0.0.1"
authors = ["Danil Gulin <d.nk.gulin@gmail.com>"]
edition = "2021"
license = "MIT"
description = "A crate with smoke tests of the `ffi_reflect`"

[dependencies]
ffi_reflect = {path = ".."}